import {
  ClerkProvider,
} from '@clerk/nextjs'


import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import MoblileNavbar from "./components/MobileNavbar";
import Footer from "./components/Footer";
export const metadata: Metadata = {
  title: "Morent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        
{/*Header Components*/}
        <Navbar/>
      <MoblileNavbar/>
        {children}
{/*Footer Component*/}
        <Footer/>
      </body>
    </html>
  </ClerkProvider>
    
      
        
  
   
  );
}
